final products = [
  {
    'id': '0',
    'title': 'Mikasha standing 3D model',
    'price': '1000',
    'anime': 'AOT',
    'imageURL': 'Assets/images/AOT1.png',
  },
  {
    'id': '1',
    'title': 'Naruto doing Rasengan',
    'price': '1200',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto1.png',
  },
  {
    'id': '2',
    'title': 'Zoro standing 3D model | One Piece',
    'price': '2200',
    'anime': 'One Piece',
    'imageURL': 'Assets/images/Luffy5.png',
  },
  {
    'id': '3',
    'title': 'Luffy standing model | One Piece',
    'price': '3100',
    'anime': 'One Piece',
    'imageURL': 'Assets/images/Luffy1.png',
  },
  {
    'id': '4',
    'title': 'Goku 3D model | Dragon Ball Z',
    'price': '200',
    'anime': 'Dragon Ball Z',
    'imageURL': 'Assets/images/Goku1.png',
  },
  {
    'id': '5',
    'title': 'Ruyk 3D model, angry | Death Note',
    'price': '1900',
    'anime': 'Death Note',
    'imageURL': 'Assets/images/Death_note4.png',
  },
  {
    'id': '6',
    'title': 'Light Yagami standing 3D model | Deatrh Note',
    'price': '1400',
    'anime': 'Death Note',
    'imageURL': 'Assets/images/Death_note2.png',
  },
  {
    'id': '7',
    'title': 'L Lawlight as Shikigami',
    'price': '900',
    'anime': 'Death Note',
    'imageURL': 'Assets/images/Death_note3.png',
  },
  {
    'id': '8',
    'title': 'Goku 3D Model with RGB lights',
    'price': '5200',
    'anime': 'Dragon Ball Z',
    'imageURL': 'Assets/images/Goku2.png',
  },
  {
    'id': '9',
    'title': 'Chainsaw Man standing 3D model',
    'price': '700',
    'anime': 'Chainsaw Man',
    'imageURL': 'Assets/images/Chainsaw_man1.png',
  },
  {
    'id': '10',
    'title': 'Chainsaw Man standing 3D model | chainsaw man',
    'price': '1200',
    'anime': 'Chainsaw Man',
    'imageURL': 'Assets/images/Chainsaw_man2.png',
  },
  {
    'id': '11',
    'title': 'Goku 3D Model with mini ring light',
    'price': '3200',
    'anime': 'Dragon Ball Z',
    'imageURL': 'Assets/images/Goku3.png',
  },
  {
    'id': '12',
    'title': 'Goku 3D model with stand',
    'price': '1200',
    'anime': 'Dragon Ball Z',
    'imageURL': 'Assets/images/Goku4.png',
  },
  {
    'id': '13',
    'title': 'Luffy 3D standing Model with mini purple light',
    'price': '4000',
    'anime': 'One Piece',
    'imageURL': 'Assets/images/Luffy2.png',
  },
  {
    'id': '14',
    'title': 'Luffy 3D Model with mini purple light | Luffy smiling 3D Model',
    'price': '999',
    'anime': 'One Piece',
    'imageURL': 'Assets/images/Luffy3.png',
  },
  {
    'id': '15',
    'title': 'Naruto doing Rasengan | Naruto cool 3D Model',
    'price': '1600',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto2.png',
  },
  {
    'id': '16',
    'title': 'Naruto doing Rasengan',
    'price': '1200',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto1.png',
  },
  {
    'id': '17',
    'title': 'Naruto with musk | Naruto 3D model',
    'price': '1300',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto7.png',
  },
  {
    'id': '18',
    'title': 'Sasuke 3D Model with Blue mini light',
    'price': '3200',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto8.png',
  },
  {
    'id': '19',
    'title': 'Sakura Haruno',
    'price': '1200',
    'anime': 'Naruto',
    'imageURL': 'Assets/images/Naruto10.png',
  },
  {
    'id': '20',
    'title': 'Pikachu 3D Model',
    'price': '1200',
    'anime': 'Pokemon',
    'imageURL': 'Assets/images/Pokemon1.png',
  },
  {
    'id': '21',
    'title': 'Pokemon 3D Mode;',
    'price': '1700',
    'anime': 'Pokemon',
    'imageURL': 'Assets/images/Pokemon2.png',
  },
];
